<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>

        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile></PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FastEndpoints.Testing" />
        <PackageReference Include="FluentAssertions" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Respawn" />
        <PackageReference Include="Testcontainers.Minio" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" >
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" >
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CnqsWebBackend\CnqsWebBackend.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Flows\Space_free.png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
