/* tslint:disable */
/* eslint-disable */
/**
 * CloudNativeQuickShare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFileResponse
 */
export interface CreateFileResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateFileResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFileResponse
     */
    uploadUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateFileResponse
     */
    uploadUrlExpires?: Date;
}

/**
 * Check if a given object implements the CreateFileResponse interface.
 */
export function instanceOfCreateFileResponse(value: object): boolean {
    return true;
}

export function CreateFileResponseFromJSON(json: any): CreateFileResponse {
    return CreateFileResponseFromJSONTyped(json, false);
}

export function CreateFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'uploadUrl': json['uploadUrl'] == null ? undefined : json['uploadUrl'],
        'uploadUrlExpires': json['uploadUrlExpires'] == null ? undefined : (new Date(json['uploadUrlExpires'])),
    };
}

export function CreateFileResponseToJSON(value?: CreateFileResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'uploadUrl': value['uploadUrl'],
        'uploadUrlExpires': value['uploadUrlExpires'] == null ? undefined : ((value['uploadUrlExpires']).toISOString()),
    };
}

