/* tslint:disable */
/* eslint-disable */
/**
 * CloudNativeQuickShare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFileRequest
 */
export interface CreateFileRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateFileRequest
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFileRequest
     */
    displayName?: string;
}

/**
 * Check if a given object implements the CreateFileRequest interface.
 */
export function instanceOfCreateFileRequest(value: object): boolean {
    return true;
}

export function CreateFileRequestFromJSON(json: any): CreateFileRequest {
    return CreateFileRequestFromJSONTyped(json, false);
}

export function CreateFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
    };
}

export function CreateFileRequestToJSON(value?: CreateFileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'clientId': value['clientId'],
        'displayName': value['displayName'],
    };
}

