/* tslint:disable */
/* eslint-disable */
/**
 * CloudNativeQuickShare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListFilesFileModel
 */
export interface ListFilesFileModel {
    /**
     * 
     * @type {string}
     * @memberof ListFilesFileModel
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFilesFileModel
     */
    shareLink?: string;
}

/**
 * Check if a given object implements the ListFilesFileModel interface.
 */
export function instanceOfListFilesFileModel(value: object): boolean {
    return true;
}

export function ListFilesFileModelFromJSON(json: any): ListFilesFileModel {
    return ListFilesFileModelFromJSONTyped(json, false);
}

export function ListFilesFileModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFilesFileModel {
    if (json == null) {
        return json;
    }
    return {
        
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'shareLink': json['shareLink'] == null ? undefined : json['shareLink'],
    };
}

export function ListFilesFileModelToJSON(value?: ListFilesFileModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fileName': value['fileName'],
        'shareLink': value['shareLink'],
    };
}

