/* tslint:disable */
/* eslint-disable */
/**
 * CloudNativeQuickShare API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListFilesFileModel } from './ListFilesFileModel';
import {
    ListFilesFileModelFromJSON,
    ListFilesFileModelFromJSONTyped,
    ListFilesFileModelToJSON,
} from './ListFilesFileModel';

/**
 * 
 * @export
 * @interface ListFilesResponse
 */
export interface ListFilesResponse {
    /**
     * 
     * @type {Array<ListFilesFileModel>}
     * @memberof ListFilesResponse
     */
    files?: Array<ListFilesFileModel>;
}

/**
 * Check if a given object implements the ListFilesResponse interface.
 */
export function instanceOfListFilesResponse(value: object): boolean {
    return true;
}

export function ListFilesResponseFromJSON(json: any): ListFilesResponse {
    return ListFilesResponseFromJSONTyped(json, false);
}

export function ListFilesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFilesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(ListFilesFileModelFromJSON)),
    };
}

export function ListFilesResponseToJSON(value?: ListFilesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(ListFilesFileModelToJSON)),
    };
}

