@CnqsWebBackend_HostAddress = http://localhost:5041

POST {{CnqsWebBackend_HostAddress}}/api/user/create
Content-Type: application/json
Accept: application/json

{
  "firstName": "string2",
  "lastName": "string3",
  "age": 22
}

###

POST {{CnqsWebBackend_HostAddress}}/api/user/create
Content-Type: application/json
Accept: application/json

{
  "firstName": "string",
  "lastName": "string",
  "age": 0
}
